/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ActiveX { 
  ENABLED, NOT_SUPPORTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActiveX\",\"namespace\":\"sessions\",\"symbols\":[\"ENABLED\",\"NOT_SUPPORTED\"],\"default\":\"NOT_SUPPORTED\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
