/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ImpressionType { 
  ACTION, VDP, SRP, THANK_YOU  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ImpressionType\",\"namespace\":\"sessions\",\"symbols\":[\"ACTION\",\"VDP\",\"SRP\",\"THANK_YOU\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
